objects = 2.59.o 2.60.o 2.61.o 2.62.o 2.63.o 2.64.o 2.65.o 2.66.o 2.67.o

all : $(objects)
2.67.o:
	gcc -m32 -c 2.67.c -o 2.67.o
$(objects) : ch2_homework.h
# 2.59.o :
# 2.60.o :
# 2.61.o :
# 2.62.o :
# 2.63.o :
# 2.64.o :
# 2.65.o :

.PHONY : clean
clean :
	rm $(objects)
